# Generated by Django 4.0.6 on 2022-07-11 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.Recipe.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_minutes', models.IntegerField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(null=True, upload_to=recipes.Recipe.models.recipe_image_file_path)),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient')),
                ('steps', models.ManyToManyField(to='recipes.step')),
                ('tags', models.ManyToManyField(to='recipes.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
