# Generated by Django 4.0.6 on 2022-07-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_description_alter_recipe_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(blank=True, to='recipes.step'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='recipes.tag'),
        ),
    ]
